### ISSUE TITLE
Strange vector problems when the VectorMasterView size changes

### ISSUE THREAD

**Issue by rubenspischedda** [harjot-oberai/VectorMaster#11]
I have a VectorMasterView inside a ConstraintLayout, with all sides constrained to parent, and width and height set to match_constraint. I've noticed that if the width or the height of the VectorMasterView change, the vector inside either disappears or is not rendered properly (e.g., the vector is oversized, is undersized, is not centered anymore).

The only way I found to prevent this behavior is to set a fixed width and a fixed height, but it's not what I need.

Is there anything I can do?

**Comment by rubenspischedda** [comment]
This is my vector:

<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="36dp"
    android:height="72dp"
    android:viewportWidth="36.0"
    android:viewportHeight="72.0">

    <path
        android:name="background"
        android:pathData="  M6,2 A4,4 0 0 0 2,6
                            L2,66 A4,4 0 0 0 6,70
                            L30,70 A4,4 0 0 0 34,66
                            L34,6 A4,4 0 0 0 30,2"
        android:strokeLineCap="round"
        android:fillColor="#222222"
        android:strokeWidth="0.6"
        android:strokeLineJoin="round"/>

    <clip-path
        android:name="mask"
        android:pathData="  M6,2 A4,4 0 0 0 2,6
                            L2,66 A4,4 0 0 0 6,70
                            L30,70 A4,4 0 0 0 34,66
                            L34,6 A4,4 0 0 0 30,2"
        android:strokeLineCap="round"
        android:fillColor="#fff"
        android:strokeLineJoin="round"/>

    <path
        android:name="foreground"
        android:pathData="M18,2 L2,2 L2,70 L34,70 L34,2 Z"
        android:strokeLineCap="round"
        android:fillColor="#14a"
        android:strokeLineJoin="round" />
</vector>

**Comment by harjot-oberai** [comment]
I have updated to `v1.1.3`. Please test with the updated code.

**Comment by harjot-oberai** [comment]
Well, did it solve your problem ?

**Comment by rubenspischedda** [comment]
Yes, it works now.
Sorry for the delay, but I was using this library at work, and I had to find a different solution. I had the opportunity to try `1.1.3` just now.

Thank you
