### ISSUE TITLE
How to use Paint with VectorMasterDrawable?

### ISSUE THREAD

**Issue by KirillJJ** [harjot-oberai/VectorMaster#6]
Hi, thanks for this awesome library.
I am using VectorMasterDrawable with Paint to set color with ColorFilter, but nothing is drawing. What i do wrong?
All is ok, if i use setColor(), but I need ColorFilter.

**Comment by harjot-oberai** [comment]
Sorry for the delayed response, but can you post the code which you are using to set the ColorFilter ?

**Comment by harjot-oberai** [comment]
Closing issue for now, reopen if you want me to look at it again.
