### ISSUE TITLE
Vector drawable not drawn properly

### ISSUE THREAD

**Issue by hivian** [harjot-oberai/VectorMaster#7]
Hi. 

I'm having a display bug when I want to use this vector drawable (SVG file exported with Adobe Illustrator, then converted to VectorDrawable) in a VectorMasterDrawable object. Some paths are missing or deformed, but only with your library, not with the Android drawable API. Can you explain me why ?

[ic_201.zip](https://github.com/harjot-oberai/VectorMaster/files/1589188/ic_201.zip)

Thank you in advance.

**Comment by harjot-oberai** [comment]
For the functionalities provided by the library, I had to parse the XML manually, but all the path parsing code has been shifted to native after API 21 and hence could not be used directly in the library. Therefore the code for parsing the xml is somewhat outdated even though I tried to port some changes from native back to java.

So the drawable API in android is updated and hence draws the vector perfectly, but the path parser I use is from API 21, therefore it is not able to draw the vector properly.

You may try to set `use_legacy_parser="false"`. Setting this parameter will make the library use a 3rd party Path Parser for parsing the xml and it may render the vector properly.

I will have a look at the vector and try to change the parsing logic to remove the errors.

Cheers!

**Comment by hivian** [comment]
I tried using `setUseLegacyParser(boolean)`. Here is the result:

**Android drawable api**

![screen shot 2017-12-28 at 12 27 06](https://user-images.githubusercontent.com/9741252/34409533-99358462-ebca-11e7-9ff1-b7ab741f3751.png)

**use_legacy_parser="true"**

![screen shot 2017-12-28 at 12 18 50](https://user-images.githubusercontent.com/9741252/34409399-eaec9c74-ebc9-11e7-92a9-f3741643b181.png)

**use_legacy_parser="false"**

![screen shot 2017-12-28 at 12 18 12](https://user-images.githubusercontent.com/9741252/34409409-f6cd547a-ebc9-11e7-86b6-f72fd87964b3.png)

It is better but somme imperfections subsist.

Anyway, thanks for your hard work!
